# Site settings
title: 5G India Forum
email: contact@5gindiaforum.com
description: > # this means to ignore newlines until "baseurl:"
 Creative is a one page Bootstrap theme for creatives, small businesses, and other multipurpose uses.
 The theme includes a number of rich features and plugins that you can use as a great boilerplate for your next Jekyll project!

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blogs.sendildevar.in" # the base hostname & protocol for your site

twitter_username: 5gindiaforum
github_username:  5gif

# Build settings
markdown: kramdown
